/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/Analytics/topology": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    environment?: string;
                    datacenterId?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/Analytics/dependencies": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    environment?: string;
                    datacenterId?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/Applications": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ApplicationResponseDto"][];
                        "application/json": components["schemas"]["ApplicationResponseDto"][];
                        "text/json": components["schemas"]["ApplicationResponseDto"][];
                    };
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreateApplicationDto"];
                    "text/json": components["schemas"]["CreateApplicationDto"];
                    "application/*+json": components["schemas"]["CreateApplicationDto"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/Datacenters": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["Datacenter"][];
                        "application/json": components["schemas"]["Datacenter"][];
                        "text/json": components["schemas"]["Datacenter"][];
                    };
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreateDatacenterDto"];
                    "text/json": components["schemas"]["CreateDatacenterDto"];
                    "application/*+json": components["schemas"]["CreateDatacenterDto"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["Datacenter"];
                        "application/json": components["schemas"]["Datacenter"];
                        "text/json": components["schemas"]["Datacenter"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/Servers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    environment?: string;
                    datacenterId?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["ServerResponseDto"][];
                        "application/json": components["schemas"]["ServerResponseDto"][];
                        "text/json": components["schemas"]["ServerResponseDto"][];
                    };
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CreateServerDto"];
                    "text/json": components["schemas"]["CreateServerDto"];
                    "application/*+json": components["schemas"]["CreateServerDto"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/Topology/tree": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: {
                    datacenterId?: string;
                    skip?: number | string;
                    take?: number | string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["TopologyTreeDto"][];
                        "application/json": components["schemas"]["TopologyTreeDto"][];
                        "text/json": components["schemas"]["TopologyTreeDto"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/Topology/map": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["DependencyMapDto"];
                        "application/json": components["schemas"]["DependencyMapDto"];
                        "text/json": components["schemas"]["DependencyMapDto"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        AppDependency: unknown;
        Application: {
            /** Format: uuid */
            id?: string;
            appCode?: string;
            appName?: string;
            /** Format: uuid */
            ownerId?: string;
            /** Format: int32 */
            portNumber?: number | string;
            protocol?: string;
            risk?: string;
            icon?: string;
            techStack?: string;
            riskLevel?: components["schemas"]["RiskLevel"];
            /** Format: uuid */
            targetApplicationId?: null | string;
            /** Format: uuid */
            serverId?: string;
            targetApplication?: null | components["schemas"]["Application"];
            server?: null | components["schemas"]["Server"];
            portMappings?: unknown;
            dependencies?: unknown;
            dependents?: unknown;
            sourceDependencies?: unknown;
            destinationDependencies?: unknown;
        };
        ApplicationNodeDto: {
            /** Format: uuid */
            id?: string;
            name?: string;
            /** Format: int32 */
            port?: number | string;
            protocol?: string;
            riskLevel?: string;
        };
        ApplicationOnServerDto: {
            /** Format: uuid */
            id?: string;
            appCode?: string;
            appName?: string;
            /** Format: uuid */
            ownerId?: string;
            /** Format: int32 */
            portNumber?: number | string;
            protocol?: string;
        };
        ApplicationResponseDto: {
            /** Format: uuid */
            id?: string;
            appCode?: string;
            appName?: string;
            /** Format: uuid */
            ownerId?: string;
            risk?: string;
            icon?: string;
            techStack?: string;
        };
        ConnectionDto: {
            /** Format: uuid */
            sourceAppId?: string;
            /** Format: uuid */
            targetAppId?: string;
        };
        CreateApplicationDto: {
            appCode?: string;
            appName?: string;
            /** Format: uuid */
            ownerId?: string;
            /** Format: int32 */
            portNumber?: number | string;
            protocol?: string;
            risk?: string;
            icon?: string;
            techStack?: string;
            riskLevel?: components["schemas"]["RiskLevel"];
            /** Format: uuid */
            targetApplicationId?: null | string;
            /** Format: uuid */
            serverId?: string;
        };
        CreateDatacenterDto: {
            name?: string;
            location?: string;
        };
        CreateServerDto: {
            /** Format: uuid */
            datacenterId?: string;
            ipAddress?: string;
            hostname?: string;
            osType?: string;
            environment?: string;
            datacenter?: string;
            status?: string;
        };
        Datacenter: {
            /** Format: uuid */
            id?: string;
            name?: string;
            location?: string;
            servers?: components["schemas"]["Server"][];
        };
        DependencyMapDto: {
            servers?: components["schemas"]["ServerNodeDto"][];
            connections?: components["schemas"]["ConnectionDto"][];
        };
        PortMapping: {
            /** Format: uuid */
            id?: string;
            /** Format: uuid */
            serverId?: string;
            /** Format: uuid */
            appId?: string;
            /** Format: int32 */
            portNumber?: number | string;
            protocol?: string;
            server?: null | components["schemas"]["Server"];
            application?: null | components["schemas"]["Application"];
            appDependencies?: components["schemas"]["AppDependency"][];
        };
        RiskLevel: number;
        Server: {
            /** Format: uuid */
            id?: string;
            /** Format: uuid */
            datacenterId?: string;
            datacenter?: null | components["schemas"]["Datacenter"];
            ipAddress?: string;
            hostname?: string;
            osType?: string;
            environment?: string;
            status?: string;
            portMappings?: components["schemas"]["PortMapping"][];
            applications?: components["schemas"]["Application"][];
        };
        ServerNodeDto: {
            /** Format: uuid */
            id?: string;
            hostname?: string;
            ipAddress?: string;
            applications?: components["schemas"]["ApplicationNodeDto"][];
        };
        ServerResponseDto: {
            /** Format: uuid */
            id?: string;
            /** Format: uuid */
            datacenterId?: string;
            ipAddress?: string;
            hostname?: string;
            osType?: string;
            environment?: string;
            datacenter?: string;
            status?: string;
            applications?: components["schemas"]["ApplicationOnServerDto"][];
        };
        TopologyTreeDto: {
            /** Format: uuid */
            id?: string;
            name?: string;
            location?: string;
            servers?: components["schemas"]["ServerNodeDto"][];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
